### ISSUE TITLE
Error on collect_swap

### ISSUE THREAD

**Issue by femixos** [versumstudios/report-bugs#85] opened 2022-02-20 01:32 UTC
{
  "props": {
    "amount": 1,
    "swap_id": 26036
  },
  "send": {
    "amount": 1000000,
    "mutez": true,
    "storageLimit": 250
  },
  "error": {
    "name": "ParametersInvalidBeaconError",
    "title": "Parameters Invalid",
    "message": "[PARAMETERS_INVALID_ERROR]:Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again.",
    "description": "Some of the parameters you provided are invalid and the request could not be completed. Please check your inputs and try again."
  },
  "message": "Error on collect_swap"
}

**Comment by skenaja** [comment] 2022-02-20 15:05
This was due to attempting to collect a time-limited swap which had expired. Duplicate of #66

**Closed as completed by skenaja** 2022-02-20 15:05 UTC
