### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by yogapratamah** [versumstudios/report-bugs#86] opened 2022-02-24 14:54 UTC
**Is your feature request related to a problem? Please describe.**
The search box will help us to find collections, art, or artists

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andrevenancio** [comment] 2022-03-03 00:21
duplicate of [https://github.com/versumstudios/report-issues/issues/83](https://github.com/versumstudios/report-issues/issues/83)

**Comment by andrevenancio** [comment] 2022-03-03 00:21
closing it, but you can follow progress on #83

**Closed as completed by andrevenancio** 2022-03-03 00:21 UTC
Labels: duplicate, enhancement
